<?php
declare(strict_types=1);

namespace App\Controller;

class OwnerController extends AppController{

    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Car');
    }

    public function index(){

//        $owner = $this->paginate($this->Owner);


        $owner = $this->Owner->find('all', ['contain' => ['Car']])->all();
////        $owner = $this->Owner->find('all', ['contain' => ['Car']])->where(['Owner.oid' => $id]);
//        echo '<pre>';print_r($owner);die();
//
//        $this->set(compact('owner'));
        $this->set(compact('owner'));
    }

    public function view($id = null){
        $owner = $this->Owner->get($id, [
            'contain' => ['Car'],
        ]);
//        $owner = $this->Owner->find('all', ['contain' => ['Car']]);
//        echo '<pre>';print_r($owner);die();
        $this->set(compact('owner'));
    }

    public function add(){

//        $model = $this->Owner->find('all', ['contain' => ['Car']])->all();
        $model = $this->Car->find('all')->all();
//        echo '<pre>';print_r($model);die();

        $owner = $this->Owner->newEmptyEntity();
        if ($this->request->is('post')){
            $owner = $this->Owner->patchEntity($owner, $this->request->getData());
            if ($this->Owner->save($owner)){
                $this->Flash->success(__('Car Owner infos Submited'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('Try Again !'));
        }
        $this->set(compact('owner', 'model'));
    }

    public function edit($id = null){

//        $model = $this->Owner->find('all', ['contain' => ['Car']])->all();
        $model = $this->Car->find('all')->all();
        $owner = $this->Owner->get($id, [
            'contain' => [],
        ]);
        if ($this->request->is(['patch', 'post', 'put'])){
            $owner = $this->Owner->patchEntity($owner, $this->request->getData());
            if ($this->Owner->save($owner)){
                $this->Flash->success(__("Updated"));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__("Try Again"));
        }
        $this->set(compact('owner', 'model'));
    }

    public function delete($id = null){
        $this->request->allowMethod(['post', 'delete']);
        $owner = $this->Owner->get($id);
        if ($this->Owner->delete($owner)){
            $this->Flash->success(__('Deleted Successfully'));
        }
        else{
            $this->Flash->error(__('Try Again'));
        }

        return $this->redirect(['action' => 'index']);
    }
}


